"""
This type stub file was generated by pyright.
"""

from django import forms
from django.db import models
from .widgets import CKEditorWidget

class RichTextField(models.TextField):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def formfield(self, **kwargs): # -> Any:
        ...
    


class RichTextFormField(forms.CharField):
    widget = CKEditorWidget
    def __init__(self, config_name=..., extra_plugins=..., external_plugin_resources=..., *args, **kwargs) -> None:
        ...
    


