"""
This type stub file was generated by pyright.
"""

from django import forms
from django.core.serializers.json import DjangoJSONEncoder

class LazyEncoder(DjangoJSONEncoder):
    def default(self, obj): # -> Any:
        ...
    


json_encode = ...
class CKEditorWidget(forms.Textarea):
    """
    Widget providing CKEditor for Rich Text Editing.
    Supports direct image uploads and embed.
    """
    template_name = ...
    def __init__(self, config_name=..., extra_plugins=..., external_plugin_resources=..., *args, **kwargs) -> None:
        ...
    
    @property
    def media(self): # -> Media:
        ...
    
    def get_context(self, name, value, attrs): # -> Dict[str, Any]:
        ...
    


