#Config Entries

news_url="https://news.google.com/search?q=ideas2it&hl=en-IN&gl=IN"
article_class="ipQwMb ekueJc RD0gLb"
image_class="tvs3Id QwxBBf"
article_link="https://news.google.com"
log_folder="log_files"
