# Generated by Django 4.2 on 2023-05-12 02:49

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(default='images/post.png', upload_to='images/post')),
                ('date', models.DateField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(100)])),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.author')),
            ],
        ),
    ]
