# Generated by Django 4.2 on 2023-05-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
    ]
